name: d2a2_3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cycler==0.11.0
    - dcn==1.0
    - docker-pycreds==0.4.0
    - einops==0.6.1
    - filelock==3.12.2
    - fonttools==4.38.0
    - fsspec==2023.1.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - huggingface-hub==0.16.4
    - idna==3.7
    - imageio==2.31.2
    - importlib-metadata==6.7.0
    - kiwisolver==1.4.5
    - matplotlib==3.5.3
    - networkx==2.6.3
    - numpy==1.21.6
    - opencv-python-headless==4.10.0.84
    - packaging==24.0
    - pillow==9.5.0
    - platformdirs==4.0.0
    - protobuf==4.24.4
    - psutil==6.0.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pywavelets==1.3.0
    - pyyaml==6.0.1
    - regex==2024.4.16
    - requests==2.31.0
    - safetensors==0.4.3
    - scikit-image==0.19.3
    - scipy==1.7.3
    - sentry-sdk==2.10.0
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - thop==0.1.1-2209072238
    - tifffile==2021.11.2
    - tokenizers==0.13.3
    - torch==1.8.0+cu111
    - torchaudio==0.8.0
    - torchsummary==1.5.1
    - torchvision==0.9.0+cu111
    - tqdm==4.66.4
    - transformers==4.30.2
    - typing-extensions==4.7.1
    - urllib3==2.0.7
    - wandb==0.17.4
    - zipp==3.15.0
prefix: /home/zyl/anaconda3/envs/d2a2_3

